name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore JokesOnYou.Web.Api
      working-directory: JokesOnYou/Server/JokesOnYou.Web.Api
    - name: Build
      run: dotnet build JokesOnYou.Web.Api --no-restore
    - name: Test
      run: dotnet test JokesOnYou.Web.Api --no-build --verbosity normal
