name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Open Client Directory
      working-directory: src
      run: |
        ls -la
    - name: Restore dependencies
      run: dotnet restore
      working-directory: JokesOnYou.Web.Api
    - name: Build
      run: dotnet build --no-restore
      working-directory: JokesOnYou.Web.Api
    - name: Test
      run: dotnet test JokesOnYou.Web.Api --no-build --verbosity normal
      working-directory: JokesOnYou.Web.Api
